import type { Metadata } from "next";
import { Inter, Nanum_Myeongjo, Do_Hyeon } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | ToDo Calendar",
    default: "ToDo Calendar"
  },
  description: "Generated by create next app",
};

const myeongjo = Nanum_Myeongjo({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--mj"
});

const dohyun = Do_Hyeon({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--dh"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myeongjo.variable} ${dohyun.variable} font-mj`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
